version: "3"
services:
  appserver-jdbc:
    image: appserver-jdbc
    ports:
      - "8080:8080"
    networks:
      - appserver-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - appserver-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_server

networks:
  appserver-mysql: